/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SemanaRouteImport } from './routes/semana'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as PapeisRouteImport } from './routes/papeis'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetosIdRouteImport } from './routes/projetos.$id'
import { Route as ApiPublicOutlookRouteImport } from './routes/api/public/outlook'
import { Route as ApiPublicMayaRouteImport } from './routes/api/public/maya'
import { Route as ApiPublicOutlookCallbackRouteImport } from './routes/api/public/outlook/callback'

const SemanaRoute = SemanaRouteImport.update({
  id: '/semana',
  path: '/semana',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const PapeisRoute = PapeisRouteImport.update({
  id: '/papeis',
  path: '/papeis',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIdRoute = ProjetosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjetosRoute,
} as any)
const ApiPublicOutlookRoute = ApiPublicOutlookRouteImport.update({
  id: '/api/public/outlook',
  path: '/api/public/outlook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMayaRoute = ApiPublicMayaRouteImport.update({
  id: '/api/public/maya',
  path: '/api/public/maya',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOutlookCallbackRoute =
  ApiPublicOutlookCallbackRouteImport.update({
    id: '/callback',
    path: '/callback',
    getParentRoute: () => ApiPublicOutlookRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/kanban': typeof KanbanRoute
  '/papeis': typeof PapeisRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/semana': typeof SemanaRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/api/public/maya': typeof ApiPublicMayaRoute
  '/api/public/outlook': typeof ApiPublicOutlookRouteWithChildren
  '/api/public/outlook/callback': typeof ApiPublicOutlookCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/kanban': typeof KanbanRoute
  '/papeis': typeof PapeisRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/semana': typeof SemanaRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/api/public/maya': typeof ApiPublicMayaRoute
  '/api/public/outlook': typeof ApiPublicOutlookRouteWithChildren
  '/api/public/outlook/callback': typeof ApiPublicOutlookCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/kanban': typeof KanbanRoute
  '/papeis': typeof PapeisRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/semana': typeof SemanaRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/api/public/maya': typeof ApiPublicMayaRoute
  '/api/public/outlook': typeof ApiPublicOutlookRouteWithChildren
  '/api/public/outlook/callback': typeof ApiPublicOutlookCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/auth'
    | '/kanban'
    | '/papeis'
    | '/projetos'
    | '/semana'
    | '/projetos/$id'
    | '/api/public/maya'
    | '/api/public/outlook'
    | '/api/public/outlook/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/auth'
    | '/kanban'
    | '/papeis'
    | '/projetos'
    | '/semana'
    | '/projetos/$id'
    | '/api/public/maya'
    | '/api/public/outlook'
    | '/api/public/outlook/callback'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/auth'
    | '/kanban'
    | '/papeis'
    | '/projetos'
    | '/semana'
    | '/projetos/$id'
    | '/api/public/maya'
    | '/api/public/outlook'
    | '/api/public/outlook/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AuthRoute: typeof AuthRoute
  KanbanRoute: typeof KanbanRoute
  PapeisRoute: typeof PapeisRoute
  ProjetosRoute: typeof ProjetosRouteWithChildren
  SemanaRoute: typeof SemanaRoute
  ApiPublicMayaRoute: typeof ApiPublicMayaRoute
  ApiPublicOutlookRoute: typeof ApiPublicOutlookRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/semana': {
      id: '/semana'
      path: '/semana'
      fullPath: '/semana'
      preLoaderRoute: typeof SemanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papeis': {
      id: '/papeis'
      path: '/papeis'
      fullPath: '/papeis'
      preLoaderRoute: typeof PapeisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$id': {
      id: '/projetos/$id'
      path: '/$id'
      fullPath: '/projetos/$id'
      preLoaderRoute: typeof ProjetosIdRouteImport
      parentRoute: typeof ProjetosRoute
    }
    '/api/public/outlook': {
      id: '/api/public/outlook'
      path: '/api/public/outlook'
      fullPath: '/api/public/outlook'
      preLoaderRoute: typeof ApiPublicOutlookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/maya': {
      id: '/api/public/maya'
      path: '/api/public/maya'
      fullPath: '/api/public/maya'
      preLoaderRoute: typeof ApiPublicMayaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/outlook/callback': {
      id: '/api/public/outlook/callback'
      path: '/callback'
      fullPath: '/api/public/outlook/callback'
      preLoaderRoute: typeof ApiPublicOutlookCallbackRouteImport
      parentRoute: typeof ApiPublicOutlookRoute
    }
  }
}

interface ProjetosRouteChildren {
  ProjetosIdRoute: typeof ProjetosIdRoute
}

const ProjetosRouteChildren: ProjetosRouteChildren = {
  ProjetosIdRoute: ProjetosIdRoute,
}

const ProjetosRouteWithChildren = ProjetosRoute._addFileChildren(
  ProjetosRouteChildren,
)

interface ApiPublicOutlookRouteChildren {
  ApiPublicOutlookCallbackRoute: typeof ApiPublicOutlookCallbackRoute
}

const ApiPublicOutlookRouteChildren: ApiPublicOutlookRouteChildren = {
  ApiPublicOutlookCallbackRoute: ApiPublicOutlookCallbackRoute,
}

const ApiPublicOutlookRouteWithChildren =
  ApiPublicOutlookRoute._addFileChildren(ApiPublicOutlookRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AuthRoute: AuthRoute,
  KanbanRoute: KanbanRoute,
  PapeisRoute: PapeisRoute,
  ProjetosRoute: ProjetosRouteWithChildren,
  SemanaRoute: SemanaRoute,
  ApiPublicMayaRoute: ApiPublicMayaRoute,
  ApiPublicOutlookRoute: ApiPublicOutlookRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
