/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SemanaRouteImport } from './routes/semana'
import { Route as PapeisRouteImport } from './routes/papeis'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetosIndexRouteImport } from './routes/projetos.index'
import { Route as ProjetosIdRouteImport } from './routes/projetos.$id'
import { Route as ApiPublicPlannerRouteImport } from './routes/api/public/planner'
import { Route as ApiPublicOutlookRouteImport } from './routes/api/public/outlook'
import { Route as ApiPublicMcpRouteImport } from './routes/api/public/mcp'
import { Route as ApiPublicMayaRouteImport } from './routes/api/public/maya'
import { Route as ApiPublicOutlookCallbackRouteImport } from './routes/api/public/outlook/callback'
import { Route as ApiPublicInboxTagEmailRouteImport } from './routes/api/public/inbox/tag-email'
import { Route as ApiPublicInboxScanRouteImport } from './routes/api/public/inbox/scan'

const SemanaRoute = SemanaRouteImport.update({
  id: '/semana',
  path: '/semana',
  getParentRoute: () => rootRouteImport,
} as any)
const PapeisRoute = PapeisRouteImport.update({
  id: '/papeis',
  path: '/papeis',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIndexRoute = ProjetosIndexRouteImport.update({
  id: '/projetos/',
  path: '/projetos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIdRoute = ProjetosIdRouteImport.update({
  id: '/projetos/$id',
  path: '/projetos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlannerRoute = ApiPublicPlannerRouteImport.update({
  id: '/api/public/planner',
  path: '/api/public/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOutlookRoute = ApiPublicOutlookRouteImport.update({
  id: '/api/public/outlook',
  path: '/api/public/outlook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMcpRoute = ApiPublicMcpRouteImport.update({
  id: '/api/public/mcp',
  path: '/api/public/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMayaRoute = ApiPublicMayaRouteImport.update({
  id: '/api/public/maya',
  path: '/api/public/maya',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOutlookCallbackRoute =
  ApiPublicOutlookCallbackRouteImport.update({
    id: '/callback',
    path: '/callback',
    getParentRoute: () => ApiPublicOutlookRoute,
  } as any)
const ApiPublicInboxTagEmailRoute = ApiPublicInboxTagEmailRouteImport.update({
  id: '/api/public/inbox/tag-email',
  path: '/api/public/inbox/tag-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInboxScanRoute = ApiPublicInboxScanRouteImport.update({
  id: '/api/public/inbox/scan',
  path: '/api/public/inbox/scan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/inbox': typeof InboxRoute
  '/papeis': typeof PapeisRoute
  '/semana': typeof SemanaRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/projetos/': typeof ProjetosIndexRoute
  '/api/public/maya': typeof ApiPublicMayaRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/outlook': typeof ApiPublicOutlookRouteWithChildren
  '/api/public/planner': typeof ApiPublicPlannerRoute
  '/api/public/inbox/scan': typeof ApiPublicInboxScanRoute
  '/api/public/inbox/tag-email': typeof ApiPublicInboxTagEmailRoute
  '/api/public/outlook/callback': typeof ApiPublicOutlookCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/inbox': typeof InboxRoute
  '/papeis': typeof PapeisRoute
  '/semana': typeof SemanaRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/projetos': typeof ProjetosIndexRoute
  '/api/public/maya': typeof ApiPublicMayaRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/outlook': typeof ApiPublicOutlookRouteWithChildren
  '/api/public/planner': typeof ApiPublicPlannerRoute
  '/api/public/inbox/scan': typeof ApiPublicInboxScanRoute
  '/api/public/inbox/tag-email': typeof ApiPublicInboxTagEmailRoute
  '/api/public/outlook/callback': typeof ApiPublicOutlookCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/inbox': typeof InboxRoute
  '/papeis': typeof PapeisRoute
  '/semana': typeof SemanaRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/projetos/': typeof ProjetosIndexRoute
  '/api/public/maya': typeof ApiPublicMayaRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/outlook': typeof ApiPublicOutlookRouteWithChildren
  '/api/public/planner': typeof ApiPublicPlannerRoute
  '/api/public/inbox/scan': typeof ApiPublicInboxScanRoute
  '/api/public/inbox/tag-email': typeof ApiPublicInboxTagEmailRoute
  '/api/public/outlook/callback': typeof ApiPublicOutlookCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/auth'
    | '/configuracoes'
    | '/inbox'
    | '/papeis'
    | '/semana'
    | '/projetos/$id'
    | '/projetos/'
    | '/api/public/maya'
    | '/api/public/mcp'
    | '/api/public/outlook'
    | '/api/public/planner'
    | '/api/public/inbox/scan'
    | '/api/public/inbox/tag-email'
    | '/api/public/outlook/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/auth'
    | '/configuracoes'
    | '/inbox'
    | '/papeis'
    | '/semana'
    | '/projetos/$id'
    | '/projetos'
    | '/api/public/maya'
    | '/api/public/mcp'
    | '/api/public/outlook'
    | '/api/public/planner'
    | '/api/public/inbox/scan'
    | '/api/public/inbox/tag-email'
    | '/api/public/outlook/callback'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/auth'
    | '/configuracoes'
    | '/inbox'
    | '/papeis'
    | '/semana'
    | '/projetos/$id'
    | '/projetos/'
    | '/api/public/maya'
    | '/api/public/mcp'
    | '/api/public/outlook'
    | '/api/public/planner'
    | '/api/public/inbox/scan'
    | '/api/public/inbox/tag-email'
    | '/api/public/outlook/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AuthRoute: typeof AuthRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  InboxRoute: typeof InboxRoute
  PapeisRoute: typeof PapeisRoute
  SemanaRoute: typeof SemanaRoute
  ProjetosIdRoute: typeof ProjetosIdRoute
  ProjetosIndexRoute: typeof ProjetosIndexRoute
  ApiPublicMayaRoute: typeof ApiPublicMayaRoute
  ApiPublicMcpRoute: typeof ApiPublicMcpRoute
  ApiPublicOutlookRoute: typeof ApiPublicOutlookRouteWithChildren
  ApiPublicPlannerRoute: typeof ApiPublicPlannerRoute
  ApiPublicInboxScanRoute: typeof ApiPublicInboxScanRoute
  ApiPublicInboxTagEmailRoute: typeof ApiPublicInboxTagEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/semana': {
      id: '/semana'
      path: '/semana'
      fullPath: '/semana'
      preLoaderRoute: typeof SemanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papeis': {
      id: '/papeis'
      path: '/papeis'
      fullPath: '/papeis'
      preLoaderRoute: typeof PapeisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/': {
      id: '/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof ProjetosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$id': {
      id: '/projetos/$id'
      path: '/projetos/$id'
      fullPath: '/projetos/$id'
      preLoaderRoute: typeof ProjetosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/planner': {
      id: '/api/public/planner'
      path: '/api/public/planner'
      fullPath: '/api/public/planner'
      preLoaderRoute: typeof ApiPublicPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/outlook': {
      id: '/api/public/outlook'
      path: '/api/public/outlook'
      fullPath: '/api/public/outlook'
      preLoaderRoute: typeof ApiPublicOutlookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mcp': {
      id: '/api/public/mcp'
      path: '/api/public/mcp'
      fullPath: '/api/public/mcp'
      preLoaderRoute: typeof ApiPublicMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/maya': {
      id: '/api/public/maya'
      path: '/api/public/maya'
      fullPath: '/api/public/maya'
      preLoaderRoute: typeof ApiPublicMayaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/outlook/callback': {
      id: '/api/public/outlook/callback'
      path: '/callback'
      fullPath: '/api/public/outlook/callback'
      preLoaderRoute: typeof ApiPublicOutlookCallbackRouteImport
      parentRoute: typeof ApiPublicOutlookRoute
    }
    '/api/public/inbox/tag-email': {
      id: '/api/public/inbox/tag-email'
      path: '/api/public/inbox/tag-email'
      fullPath: '/api/public/inbox/tag-email'
      preLoaderRoute: typeof ApiPublicInboxTagEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/inbox/scan': {
      id: '/api/public/inbox/scan'
      path: '/api/public/inbox/scan'
      fullPath: '/api/public/inbox/scan'
      preLoaderRoute: typeof ApiPublicInboxScanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiPublicOutlookRouteChildren {
  ApiPublicOutlookCallbackRoute: typeof ApiPublicOutlookCallbackRoute
}

const ApiPublicOutlookRouteChildren: ApiPublicOutlookRouteChildren = {
  ApiPublicOutlookCallbackRoute: ApiPublicOutlookCallbackRoute,
}

const ApiPublicOutlookRouteWithChildren =
  ApiPublicOutlookRoute._addFileChildren(ApiPublicOutlookRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AuthRoute: AuthRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  InboxRoute: InboxRoute,
  PapeisRoute: PapeisRoute,
  SemanaRoute: SemanaRoute,
  ProjetosIdRoute: ProjetosIdRoute,
  ProjetosIndexRoute: ProjetosIndexRoute,
  ApiPublicMayaRoute: ApiPublicMayaRoute,
  ApiPublicMcpRoute: ApiPublicMcpRoute,
  ApiPublicOutlookRoute: ApiPublicOutlookRouteWithChildren,
  ApiPublicPlannerRoute: ApiPublicPlannerRoute,
  ApiPublicInboxScanRoute: ApiPublicInboxScanRoute,
  ApiPublicInboxTagEmailRoute: ApiPublicInboxTagEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
