/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SemanaRouteImport } from './routes/semana'
import { Route as PapeisRouteImport } from './routes/papeis'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiOutlookCallbackRouteImport } from './routes/api/outlook/callback'

const SemanaRoute = SemanaRouteImport.update({
  id: '/semana',
  path: '/semana',
  getParentRoute: () => rootRouteImport,
} as any)
const PapeisRoute = PapeisRouteImport.update({
  id: '/papeis',
  path: '/papeis',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOutlookCallbackRoute = ApiOutlookCallbackRouteImport.update({
  id: '/api/outlook/callback',
  path: '/api/outlook/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/kanban': typeof KanbanRoute
  '/papeis': typeof PapeisRoute
  '/semana': typeof SemanaRoute
  '/api/outlook/callback': typeof ApiOutlookCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/kanban': typeof KanbanRoute
  '/papeis': typeof PapeisRoute
  '/semana': typeof SemanaRoute
  '/api/outlook/callback': typeof ApiOutlookCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/kanban': typeof KanbanRoute
  '/papeis': typeof PapeisRoute
  '/semana': typeof SemanaRoute
  '/api/outlook/callback': typeof ApiOutlookCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/auth'
    | '/kanban'
    | '/papeis'
    | '/semana'
    | '/api/outlook/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/auth'
    | '/kanban'
    | '/papeis'
    | '/semana'
    | '/api/outlook/callback'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/auth'
    | '/kanban'
    | '/papeis'
    | '/semana'
    | '/api/outlook/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AuthRoute: typeof AuthRoute
  KanbanRoute: typeof KanbanRoute
  PapeisRoute: typeof PapeisRoute
  SemanaRoute: typeof SemanaRoute
  ApiOutlookCallbackRoute: typeof ApiOutlookCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/semana': {
      id: '/semana'
      path: '/semana'
      fullPath: '/semana'
      preLoaderRoute: typeof SemanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papeis': {
      id: '/papeis'
      path: '/papeis'
      fullPath: '/papeis'
      preLoaderRoute: typeof PapeisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/outlook/callback': {
      id: '/api/outlook/callback'
      path: '/api/outlook/callback'
      fullPath: '/api/outlook/callback'
      preLoaderRoute: typeof ApiOutlookCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AuthRoute: AuthRoute,
  KanbanRoute: KanbanRoute,
  PapeisRoute: PapeisRoute,
  SemanaRoute: SemanaRoute,
  ApiOutlookCallbackRoute: ApiOutlookCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
